apiVersion: v1
kind: ConfigMap
metadata:
  name: qww-configmap
  namespace: deviceshifu
  labels:
    app: deviceshifu-qww
    workspace_id: "95562340-9bc7-4f51-88ed-a435ddb204e9"
    workspace_name: "test2"
  annotations:
    workspace.id: "95562340-9bc7-4f51-88ed-a435ddb204e9"
    workspace.name: "test2"
    template.id: "usb-gps-v1"
data:
  driverProperties: |
    driverSku: "USB GPS Device"
    driverImage: gps-nats-shifu:latest
  instructions: |
    instructions:
  telemetries: |
    telemetries:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qww
  namespace: deviceshifu
  labels:
    app: deviceshifu-qww
    workspace_id: "95562340-9bc7-4f51-88ed-a435ddb204e9"
    workspace_name: "test2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qww
  template:
    metadata:
      labels:
        app: qww
        workspace_id: "95562340-9bc7-4f51-88ed-a435ddb204e9"
        workspace_name: "test2"
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: qww
          image: edgenesis/deviceshifu-usb-gps:v0.0.1
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
            - name: serial-device
              mountPath: /dev
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-qww"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
            - name: NATS_SERVER_URL
              value: "nats://192.168.1.100:4222"
            - name: NATS_TOPIC
              value: "test2.qww.gps.data"
            - name: NATS_PUBLISH_INTERVAL
              value: "1"
            - name: BAUDRATE
              value: "9600"
      volumes:
        - name: deviceshifu-config
          configMap:
            name: qww-configmap
        - name: serial-device
          hostPath:
            path: /dev
      serviceAccountName: edgedevice-sa
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-qww
  namespace: devices
  labels:
    app: deviceshifu-qww
    workspace_id: "95562340-9bc7-4f51-88ed-a435ddb204e9"
    workspace_name: "test2"
  annotations:
    workspace.id: "95562340-9bc7-4f51-88ed-a435ddb204e9"
    workspace.name: "test2"
    template.id: "usb-gps-v1"
spec:
  sku: "USB GPS Device"
  protocol: "Serial"
  address: "/dev/ttyACM0"
  connection: "USB"
---
apiVersion: v1
kind: Service
metadata:
  name: qww-service
  namespace: deviceshifu
  labels:
    app: deviceshifu-qww
    workspace_id: "95562340-9bc7-4f51-88ed-a435ddb204e9"
    workspace_name: "test2"
spec:
  selector:
    app: qww
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: ClusterIP 