apiVersion: v1
kind: ConfigMap
metadata:
  name: devicetest1-configmap
  namespace: deviceshifu
  annotations:
    workspace.id: "fef7dfd9-376a-400d-98a3-1f4a64803f81"
    workspace.name: "test1"
data:
  driverProperties: |
    driverSku: HTTP USB Camera Device
    driverImage: edgenesis/usb-camera:v0.0.1
  instructions: |
    instructions:
      video:
      capture:
      probe:
  telemetries: |
    telemetries:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-devicetest1
    workspace.id: "fef7dfd9-376a-400d-98a3-1f4a64803f81"
    workspace.name: "test1"
  name: deviceshifu-devicetest1
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-devicetest1
  template:
    metadata:
      labels:
        app: deviceshifu-devicetest1
        workspace.id: "fef7dfd9-376a-400d-98a3-1f4a64803f81"
        workspace.name: "test1"
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:nightly
          name: deviceshifu-devicetest1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-devicetest1"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
        - image: edgenesis/usb-camera:v0.0.3
          securityContext:
            privileged: true
          name: camera-python
          env:
            - name: CAMERA_WIDTH
              value: "640"
            - name: CAMERA_HEIGHT
              value: "480"
            - name: VIDEONUMBER
              value: "0"
          volumeMounts:
            - name: video
              mountPath: "/dev"
          resources:
      volumes:
        - name: deviceshifu-config
          configMap:
            name: devicetest1-configmap
        - name: video
          hostPath:
            path: /dev
      serviceAccountName: edgedevice-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-devicetest1
    workspace.id: "fef7dfd9-376a-400d-98a3-1f4a64803f81"
    workspace.name: "test1"
  name: deviceshifu-devicetest1
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: deviceshifu-devicetest1
  type: ClusterIP
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-devicetest1
  namespace: devices
  annotations:
    workspace.id: "fef7dfd9-376a-400d-98a3-1f4a64803f81"
    workspace.name: "test1"
spec:
  sku: "HTTP USB Camera Device"
  connection: Ethernet
  address: 0.0.0.0:5001
  protocol: HTTP
