apiVersion: v1
kind: ConfigMap
metadata:
  name: deviceshifu-industrial_test-configmap
  namespace: deviceshifu
data:
  api_list.json: |
    [
      {
        "description": "Read the latest temperature (°C) and humidity (% RH) values from the last successful Modbus poll, along with a timestamp of when they were measured. Call this to display current environmental conditions; if the device is temporarily disconnected, this returns the last known values. Check /status for connection health before relying on stale data.",
        "method": "GET",
        "name": "/readings",
        "path": "/readings"
      },
      {
        "description": "Read the current runtime configuration used by the driver. Use this to audit settings before or after changes. Typical fields: sampling_interval_seconds, alarm_thresholds (temp_low, temp_high, humidity_low, humidity_high), communication (retry_count, timeout_ms).",
        "method": "GET",
        "name": "/config",
        "path": "/config"
      },
      {
        "description": "Retrieve current driver and connection status to the Modbus TCP sensor, including whether it is connected, last successful poll time, current sampling interval, and recent communication error summary. Use this to verify the driver is polling every few seconds and automatically reconnecting after network failures. Typical fields: connected, last_poll_time, sampling_interval_seconds, retry_count, timeout_ms, consecutive_failures, last_error_message.",
        "method": "GET",
        "name": "/status",
        "path": "/status"
      }
    ]
  device_endpoint: "device-endpoint-placeholder"
  device_port: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: deviceshifu-industrial_test-service
  namespace: deviceshifu
  labels:
    app: deviceshifu
    device: industrial_test
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: deviceshifu
    device: industrial_test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deviceshifu-industrial_test-deployment
  namespace: deviceshifu
  labels:
    app: deviceshifu
    device: industrial_test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu
      device: industrial_test
  template:
    metadata:
      labels:
        app: deviceshifu
        device: industrial_test
    spec:
      containers:
      - name: deviceshifu
        image: registry.test.shifu.dev/test-project/p8vmlvcxyhor5wdw7jdoj3ln2dg5/industrial_test:v0.0.8
        ports:
        - containerPort: 8080
        env:
        - name: DEVICE_NAME
          value: "Industrial Test"
        - name: DEVICE_PROTOCOL
          value: "Modbus TCP"
        - name: DEVICE_MANUFACTURER
          value: "sdf"
        - name: DEVICE_MODEL
          value: "rfrf"
        envFrom:
        - configMapRef:
            name: deviceshifu-industrial_test-configmap
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
